# Generated by Django 4.2.9 on 2024-02-28 06:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('loader', '0011_alter_uploadfiles_db_record_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('example_something_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='modeln',
            name='to_uploader',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='modelN', to='loader.uploadfiles'),
        ),
        migrations.AddField(
            model_name='modeln',
            name='to_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='modelN', to=settings.AUTH_USER_MODEL),
        ),
    ]
